language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script: 
  - asdf plugin-test swiftlint $TRAVIS_BUILD_DIR 'swiftlint version'

osx_image: xcode10.3
os:
  - osx
  # - linux