name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Shellcheck
      run: sudo apt-get install shellcheck
    - name: Lint the plugin
      run: shellcheck bin/*
      
  plugin-test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install ASDF
      run: brew install asdf
    - name: Test plugin 
      run: GITHUB_API_TOKEN=$GITHUB_TOKEN asdf plugin-test swiftlint $GITHUB_WORKSPACE 'asdf exec swiftlint version'
